language: python
# we need different executable name for 2.7 and 3.4, specify matrix explicitly: 
# see http://docs.travis-ci.com/user/customizing-the-build/
##python:
#   - 3.4
###   - 2.7
matrix:
   include:
      - python: "2.7"
        env: WOO_EXEC=woo-headless
      - python: "3.4"
        env: WOO_EXEC=woo-headless-py3
install:
   # use APT only to install c-dev things, virtualenv cannot use system-installed python modules w/ py3k at travis
   - pip install xlrd xlwt-future numpy matplotlib colorama genshi psutil minieigen imaging h5py lockfile ipython colour_runner xlsxwriter prettytable setuptools
   - WOO_FLAVOR=headless python setup.py install
script:
   - timeout 60 $WOO_EXEC --test # py3 stalls?!
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
sudo: false
addons:
   apt:
      packages:
         - python-all
         - python-all-dev
         - python3-all
         - python3-all-dev
         - libboost-all-dev
         - libvtk5-dev
         - libgts-dev
         - libeigen3-dev
