language: python
# we need different executable name for 2.7 and 3.4, specify matrix explicitly: 
# see http://docs.travis-ci.com/user/customizing-the-build/
##python:
#   - 3.4
###   - 2.7
matrix:
	include:
		- python: "2.7"
		   env: WOO_EXEC=woo
		- python: "3.4"
		   env: WOO_EXEC=woo-py3
install:
   #  APT stuff is below separately
   - pip install colour_runner # optional
   - python setup.py install
script:
   - timeout 60 $WOO_EXEC --test # py3 stalls?!
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
sudo: false
addons:
   apt:
      packages:
			# copied from debian/control mostly
 			- python-all
			- python-all-dev
			- python-setuptools
			- python3-setuptools
			- python3-all
			- python3-all-dev
			- debhelper
			- libboost-all-dev
			- pyqt4-dev-tools
			- libqt4-dev
			- libqt4-dev-bin
			- qt4-dev-tools
			- libgle3-dev
			- libqglviewer-dev
			- libqt4-opengl-dev
			- libvtk5-dev
			- libgts-dev
			- libeigen3-dev
			- freeglut3-dev
			- python-xlrd
			- python-xlwt
			- python-numpy
			- python-matplotlib
			- python-colorama
			- python-qt4
			- python-xlib
			- python-genshi
			- python-psutil
			- python-minieigen
			- python-imaging
			- python-h5py
			- python-lockfile
			- ipython
			- python3-xlrd
			- python3-xlsxwriter
			- python3-numpy
			- python3-matplotlib
			- python3-colorama
			- python3-pyqt4
			- python3-xlib
			- python3-genshi
			- python3-psutil
			- python3-minieigen
			- python3-imaging
			- python3-h5py
			- python3-lockfile
			- ipython3
			- python3-prettytable


				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
				 
    
